version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: nf-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 8882304322@Rk
      POSTGRES_DB: maindb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
